### PR TITLE
Fix incorrect reference to PROPERTY_NAMING_STRATEGY

### LINKED ISSUE #205: Mistyped documentation
https://github.com/eclipse-ee4j/jsonb-api/blob/master/api/src/main/java/javax/json/bind/JsonbConfig.java#L255

PROPERTY_NAMING_STRATEGY  instead of JSONB_PROPERTY_NAMING_STRATEGY
Other wrong name: JSONB_PROPERTY_ORDER_STRATEGY

_**Notice:**_
other use: {@link #PROPERTY_NAMING_STRATEGY} or {@link JsonbConfig#PROPERTY_NAMING_STRATEGY} instead of {@code JSONB_PROPERTY_NAMING_STRATEGY}

### PR DESCRIPTION
**Pull request by aguibert**
Fixes #205

### CODE REVIEW

**Comment by aguibert** [comment]
@m0mus or @Verdent can you please review?

File: api/src/main/java/javax/json/bind/JsonbConfig.java [hunk 1]
```diff
@@ -252,7 +252,7 @@ public final JsonbConfig withStrictIJSON(final Boolean enabled) {
     /**
      * Property used to specify custom naming strategy.
      *
-     * Configures value of {@code JSONB_PROPERTY_NAMING_STRATEGY} property.
+     * Configures value of {@link #PROPERTY_NAMING_STRATEGY} property.
```
Comment (Verdent) [inline api/src/main/java/javax/json/bind/JsonbConfig.java]: I guess this change is OK, but there are also other places in this config which should be changed because of consistency.
For example: {@ code STRICT_IJSON} etc.

Or is there a reason why to change it only in this case?

Comment (aguibert) [reply api/src/main/java/javax/json/bind/JsonbConfig.java]: good catch @Verdent. I've updated my PR and also fixed javadoc in the rest of the file

Comment (Verdent) [reply api/src/main/java/javax/json/bind/JsonbConfig.java]: @aguibert great :-)
